### ISSUE TITLE
One touch record not working

### ISSUE THREAD

**Issue by obcocav** [bitfocus/companion-module-denon-recorder#5]
@istnv 

John and any others,

Sorry to bug you again.  Finally back to doing church work and the feedback is working in the latest builds, as well as the initiate recording, pause, split etc.  The one touch record and one touch stop are not though.  One touch record >sometimes< makes the record display "completed" on screen but never records and one touch stop does nothing.  There is no "Stop" function under the "recording functions" dialog but there is an option for "2353" which I dont know what is and appears to do nothing.

Any help is greatly appreciated!

**Comment by istnv** [comment]
I think the 'one touch record' functions enable/disable one-touch, but don't start recording. They are meant to allow the record button to automatically start recording, instead of standby. Stop is the same button for play or record. '2353' is strange, it is the protocol command for 'Play' and shouldn't end up on a label.
I need to refresh my memory from the documentation.

**Comment by istnv** [comment]
**One touch record** is a switch that allows the **Record** command to start recording. Otherwise you press **Record** to enter a Record/Paused mode, then press **Record** again to start recording. By themselves OTR does nothing.
There is only one **Stop** command. It stops both Record and Playback.
The "2353" is a typo and will be fixed soon.

**Comment by obcocav** [comment]
Hey John,

Right.  One touch is what I want and what worked before.  I have just been unable to get a recording to stop at all via companion.  I can "iniate recording” with one push but no command I send stops the recording.

Thanks!

Kevin

**Comment by istnv** [comment]
Use the **Stop** from the Playback functions. It is the only STOP command on the device.
